Repository litecoin-foundation/litewallet-android, pull requests merged in 2023-05, with the labels that each got.

#141 🚀[ Release v.2.8.4] Merge into Develop
  app/build.gradle
  app/src/main/java/com/breadwallet/tools/util/BRConstants.java
  app/src/main/java/com/breadwallet/wallet/BRPeerManager.java
Labels: 🚀 release

#140 Bugfix - fix FragmentMenu crash in menuClose()
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentMenu.java
Labels: 🐛 bug, 🦺 tech debt

#143 Bugfix - Phrase Reminder crash
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentBalanceSeedReminder.kt
Labels: 🐛 bug
