Repository litecoin-foundation/litewallet-android, pull requests merged in 2024-03, with the labels that each got.

#169 [Tech Debt] Normalized working version
  app/build.gradle
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/tools/util/Utils.java
  fast_follow_asset_pack_01/build.gradle
  install_time_asset_pack/build.gradle
  settings.gradle
Labels: 🦺 tech debt

#170 Remove Opaque on IntroActivity
  app/src/main/res/layout/activity_intro.xml
Labels: 🦺 tech debt

#168 Added Announcement view to encourage email mailing list
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/breadwallet/presenter/activities/AnnounceUpdatesViewActivity.kt
  app/src/main/java/com/breadwallet/presenter/activities/intro/IntroActivity.java
  app/src/main/res/drawable/button_no_thanks_emails.xml
  app/src/main/res/layout/activity_announce_updates_view.xml
  app/src/main/res/values-land/dimens.xml
  app/src/main/res/values-w1240dp/dimens.xml
  app/src/main/res/values-w600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🥳 feature

#166 Adding a close button in the Settings Modal
  app/src/main/java/com/breadwallet/presenter/activities/DisabledActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/InputWordsActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/PaperKeyActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/PaperKeyProveActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/ReEnterPinActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/SetPinActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/UpdatePinActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/camera/CameraActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/camera/ScanQRActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/intro/IntroActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/intro/RecoverActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/intro/WriteDownActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/AboutActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/AdvancedActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/DisplayCurrencyActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/FingerprintActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/ImportActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/NodesActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/NotificationActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/SecurityCenterActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/SettingsActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/ShareDataActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/SpendLimitActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/SyncBlockchainActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/TestActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/WipeActivity.java
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentSend.kt
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_display_currency.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_spend_limit.xml
Labels: 🥳 feature, 🦺 tech debt
