Repository litecoin-foundation/litewallet-android, pull requests merged in 2024-12, with the labels that each got.

#290 Added abilities to copy transaction id by click the transaction id
  app/build.gradle
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentTransactionItem.java
Labels: 🐛 bug

#287 Unit Test(s) Migration
  .circleci/config.yml
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/androidTest/java/com/litewallet/PaperKeyTests.java
  app/src/androidTest/java/com/litewallet/analytics/ConstantsTests.java
  app/src/androidTest/java/com/litewallet/database/DatabaseTests.java
  app/src/androidTest/java/com/litewallet/platform/KVStoreTests.java
  app/src/androidTest/java/com/litewallet/platform/PlatformTests.java
  app/src/androidTest/java/com/litewallet/presenter/activities/tests/MainActivityTest.java
  app/src/androidTest/java/com/litewallet/presenter/currencyformatting/tests/CurrencyFormatterFixedTests.java
  app/src/androidTest/java/com/litewallet/presenter/currencyformatting/tests/CurrencyFormatterTests.java
  app/src/androidTest/java/com/litewallet/security/KeyStoreTests.java
  app/src/androidTest/java/com/litewallet/security/NewKeyStoreTests.java
  app/src/androidTest/java/com/litewallet/wallet/WalletTests.java
  app/src/main/java/com/breadwallet/tools/sqlite/CurrencyDataSource.java
  app/src/test/java/com/litewallet/currency/CurrencyTests.kt
  app/src/test/java/com/litewallet/example/ExampleTest.kt
  app/src/test/java/com/litewallet/tools/database/DatabaseTests.kt
  app/src/test/java/com/litewallet/tools/database/TransactionDataSourceTest.kt
  app/src/test/java/com/litewallet/tools/security/BRKeyStoreTest.kt
  app/src/test/java/com/litewallet/tools/security/NewKeyStoreTests.kt
  app/src/test/java/com/litewallet/tools/security/ReplicatedKVStoreTest.kt
  app/src/test/java/com/litewallet/tools/util/BRConstantsTest.kt
  app/src/test/java/com/litewallet/tools/util/Bip39ReaderTest.kt
  app/src/test/java/com/litewallet/tools/util/LocaleHelperTest.kt
  app/src/test/java/com/litewallet/tools/util/SeedWordTests.kt
Labels: 🏡 moderate-priority

#298 fix: just close the FragmentRequestAmount if refreshAddress return false
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentRequestAmount.java
Labels: 🐛 bug

#294 🚀[Release v2.13.0] Merge into Develop
  app/build.gradle
Labels: 🚀 release

#300 Added tests BRConstants MockK+JUnit4
  app/src/test/java/com/litewallet/tools/util/BRConstantsTest.kt
Labels: 🦺 tech debt

#299 fix: fix User unable to set preferred local fiat currency
  app/src/main/java/com/breadwallet/presenter/activities/BreadActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/DisplayCurrencyActivity.java
  app/src/main/res/layout/activity_display_currency.xml
Labels: 🐛 bug

#301 🚀[Release v2.13.0] Merge into Main
  .circleci/config.yml
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/androidTest/java/com/litewallet/PaperKeyTests.java
  app/src/androidTest/java/com/litewallet/database/DatabaseTests.java
  app/src/androidTest/java/com/litewallet/platform/KVStoreTests.java
  app/src/androidTest/java/com/litewallet/platform/PlatformTests.java
  app/src/androidTest/java/com/litewallet/presenter/activities/tests/MainActivityTest.java
  app/src/androidTest/java/com/litewallet/presenter/currencyformatting/tests/CurrencyFormatterFixedTests.java
  app/src/androidTest/java/com/litewallet/presenter/currencyformatting/tests/CurrencyFormatterTests.java
  app/src/androidTest/java/com/litewallet/security/KeyStoreTests.java
  app/src/androidTest/java/com/litewallet/security/NewKeyStoreTests.java
  app/src/androidTest/java/com/litewallet/wallet/WalletTests.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/presenter/activities/LoginActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/intro/WriteDownActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/FingerprintActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/SecurityCenterActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/SettingsActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/util/BRActivity.java
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentBuy.java
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentFingerprint.java
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentMenu.java
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentTransactionItem.java
  app/src/main/java/com/breadwallet/tools/manager/BRApiManager.java
  app/src/main/java/com/breadwallet/tools/manager/PromptManager.java
  app/src/main/java/com/breadwallet/tools/security/AuthManager.java
  app/src/main/java/com/breadwallet/tools/security/BRSender.java
  app/src/main/java/com/breadwallet/tools/sqlite/CurrencyDataSource.java
  app/src/main/java/com/breadwallet/tools/threads/PaymentProtocolTask.java
  app/src/main/java/com/breadwallet/tools/util/BRConstants.java
  app/src/main/java/com/breadwallet/tools/util/Utils.java
  app/src/main/java/com/litewallet/data/source/RemoteConfigSource.kt
  app/src/main/java/com/litewallet/di/Module.kt
  app/src/main/res/layout/activity_pin.xml
  app/src/main/res/layout/fingerprint_dialog_container.xml
  app/src/main/res/xml/remote_config_defaults.xml
  app/src/test/java/com/litewallet/currency/CurrencyTests.kt
  app/src/test/java/com/litewallet/data/source/RemoteConfigSourceFirebaseImplTest.kt
  app/src/test/java/com/litewallet/example/ExampleTest.kt
  app/src/test/java/com/litewallet/tools/database/DatabaseTests.kt
  app/src/test/java/com/litewallet/tools/database/TransactionDataSourceTest.kt
  app/src/test/java/com/litewallet/tools/manager/BRApiManagerTest.kt
  app/src/test/java/com/litewallet/tools/security/BRKeyStoreTest.kt
  app/src/test/java/com/litewallet/tools/security/NewKeyStoreTests.kt
  app/src/test/java/com/litewallet/tools/security/ReplicatedKVStoreTest.kt
  app/src/test/java/com/litewallet/tools/util/BRConstantsTest.kt
  app/src/test/java/com/litewallet/tools/util/Bip39ReaderTest.kt
  app/src/test/java/com/litewallet/tools/util/LocaleHelperTest.kt
  app/src/test/java/com/litewallet/tools/util/SeedWordTests.kt
Labels: 🚀 release

#302 fix: fix crash android.os.NetworkOnMainThreadException: onPublishTxAuth
  app/src/main/java/com/breadwallet/tools/security/BRSender.java
Labels: 🐛 bug

#303 Update NotificationHandlerTest.kt
  .circleci/config.yml
  app/build.gradle
  app/src/test/java/com/litewallet/notification/NotificationHandlerTest.kt
Labels: 🐛 bug

#304 🚀[Release v2.13.0 20241220] Merge into Develop
  README.md
Labels: android, 🚀 release

#305 feat: support arabic language
  app/src/main/java/com/breadwallet/entities/IntroLanguageResource.kt
  app/src/main/java/com/breadwallet/entities/Language.kt
  app/src/main/java/com/breadwallet/presenter/history/HistoryFragment.kt
  app/src/main/java/com/breadwallet/tools/manager/TxManager.java
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_advanced.xml
  app/src/main/res/layout/activity_bread.xml
  app/src/main/res/layout/activity_disabled.xml
  app/src/main/res/layout/activity_display_currency.xml
  app/src/main/res/layout/activity_fingerprint.xml
  app/src/main/res/layout/activity_import.xml
  app/src/main/res/layout/activity_input_words.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_intro_recover.xml
  app/src/main/res/layout/activity_nodes.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_paper_key.xml
  app/src/main/res/layout/activity_paper_key_prove.xml
  app/src/main/res/layout/activity_pin.xml
  app/src/main/res/layout/activity_pin_template.xml
  app/src/main/res/layout/activity_qr.xml
  app/src/main/res/layout/activity_restore.xml
  app/src/main/res/layout/activity_security_center.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_share_data.xml
  app/src/main/res/layout/activity_spend_limit.xml
  app/src/main/res/layout/activity_sync_blockchain.xml
  app/src/main/res/layout/activity_web_view.xml
  app/src/main/res/layout/bread_alert_dialog.xml
  app/src/main/res/layout/fragment_balance_seed_reminder.xml
  app/src/main/res/layout/fragment_bread_pin.xml
  app/src/main/res/layout/fragment_greetings.xml
  app/src/main/res/layout/fragment_menu.xml
  app/src/main/res/layout/fragment_receive.xml
  app/src/main/res/layout/fragment_send.xml
  app/src/main/res/layout/menu_list_item.xml
  app/src/main/res/layout/notification_bar.xml
  app/src/main/res/layout/prompt_item.xml
  app/src/main/res/layout/search_bar.xml
  app/src/main/res/layout/security_center_list_item.xml
  app/src/main/res/layout/syncing_item.xml
  app/src/main/res/layout/transaction_details_item.xml
  app/src/main/res/layout/tx_item.xml
  app/src/main/res/raw/arabic.mp3
  app/src/main/res/values-ar/strings.xml
  app/src/test/java/com/litewallet/tools/util/LocaleHelperTest.kt
Labels: 🥳 feature
