Repository litecoin-foundation/litewallet-android, pull requests merged in 2024-10, with the labels that each got.

#243 Update review blogic
  app/build.gradle
  app/src/androidTest/java/com/breadwallet/analytics/AnalyticsTests.java
  app/src/main/java/com/breadwallet/presenter/activities/BreadActivity.java
  app/src/main/java/com/breadwallet/tools/manager/BRSharedPrefs.java
  app/src/main/java/com/breadwallet/tools/util/BRConstants.java
Labels: 🦺 tech debt

#244 Temp branch release v2.11.1
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-tech-debt.yml
  .github/ISSUE_TEMPLATE/3-feature.yml
  .github/ISSUE_TEMPLATE/4-user-feature-request.yml
  .github/ISSUE_TEMPLATE/5-spike.yml
  .github/ISSUE_TEMPLATE/6-general-request.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/ISSUE_TEMPLATE/techdebt.md
  .github/ISSUE_TEMPLATE~56e9056c (Create ISSUE_TEMPLATE)
  .gitignore
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/evil.json
  app/src/androidTest/java/com/breadwallet/analytics/AnalyticsTests.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/presenter/activities/AnnounceUpdatesViewActivity.kt
  app/src/main/java/com/breadwallet/presenter/activities/BreadActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/intro/IntroActivity.java
  app/src/main/java/com/breadwallet/tools/manager/BRSharedPrefs.java
  app/src/main/java/com/breadwallet/tools/util/BRConstants.java
  app/src/main/res/layout/activity_announce_updates_view.xml
Labels: 🏰 high-priority, 🚀 release

#245 🚀[Release v2.11.1 071024] Merge into Develop
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/tools/security/KeyStoreManager.java
  app/src/main/jni/transition/PeerManager.c
  app/src/main/jni/transition/wallet.c
  app/src/main/res/layout/button_buy_bitcoin.xml
Labels: 🏰 high-priority, 🚀 release

#246 🚀[Release v2.11.1 071024] Merge into Main
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/tools/security/KeyStoreManager.java
  app/src/main/jni/transition/PeerManager.c
  app/src/main/jni/transition/wallet.c
  app/src/main/res/layout/button_buy_bitcoin.xml
Labels: 🏰 high-priority, 🚀 release

#247 Added Fiat feature, and FCM for push notifications
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/entities/IntroLanguageResource.kt
  app/src/main/java/com/breadwallet/presenter/activities/BreadActivity.java
  app/src/main/java/com/breadwallet/tools/util/PushNotificationService.kt
  app/src/main/res/drawable/litewallet_fin_icon_200.jpg
  app/src/main/res/drawable/litewallet_logotype_white_notifications.png
Labels: 🥳 feature

#248 Tech debt/add af sdk
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/presenter/entities/PartnerNames.kt
  app/src/main/java/com/breadwallet/tools/util/Utils.java
Labels: 🦺 tech debt

#254 Techdebt/refactor brevents syncmarkers
  .gitignore
  .idea/androidTestResultsUserPreferences.xml
  app/build.gradle
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentBalanceSeedReminder.kt
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentFingerprint.java
  app/src/main/java/com/breadwallet/presenter/history/HistoryFragment.kt
  app/src/main/java/com/breadwallet/tools/animation/BRAnimator.java
  app/src/main/java/com/breadwallet/tools/manager/BREventManager.java
  app/src/main/java/com/breadwallet/tools/manager/BRSharedPrefs.java
  app/src/main/java/com/breadwallet/tools/manager/InternetManager.java
  app/src/main/java/com/breadwallet/tools/manager/TxManager.java
  app/src/main/java/com/breadwallet/tools/security/BitcoinUrlHandler.java
  app/src/main/java/com/breadwallet/tools/util/BRConstants.java
  app/src/main/java/com/breadwallet/tools/util/Utils.java
Labels: 🦺 tech debt
