Repository litecoin-foundation/litewallet-android, pull requests merged in 2024-09, with the labels that each got.

#204 Added FCM Push Notifications
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/tools/util/PushNotificationService.kt
Labels: 🏰 high-priority, 🦺 tech debt

#205 Fixed it
  .gitignore
  app/src/main/jni/transition/wallet.c
Labels: 🐛 bug

#197 Updated target API to level 14 (SDK Version 34)
  app/build.gradle
Labels: android, 🏡 moderate-priority
