Repository litecoin-foundation/litewallet-android, pull requests merged in 2024-11, with the labels that each got.

#255 Techdebt/ fixed send issue add syncing measurements
  app/build.gradle
  app/evil.json
  app/src/canary-file.json
  app/src/main/java/com/breadwallet/BreadApp.java
  app/src/main/java/com/breadwallet/presenter/activities/BreadActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/intro/IntroActivity.java
  app/src/main/java/com/breadwallet/tools/adapter/TransactionListAdapter.java
  app/src/main/java/com/breadwallet/tools/manager/BRApiManager.java
  app/src/main/java/com/breadwallet/tools/manager/BRSharedPrefs.java
  app/src/main/java/com/breadwallet/tools/manager/SyncManager.java
  app/src/main/java/com/breadwallet/tools/manager/TxManager.java
  app/src/main/java/com/breadwallet/tools/util/Utils.java
  app/src/main/java/com/breadwallet/wallet/BRPeerManager.java
  app/src/main/java/com/breadwallet/wallet/BRWalletManager.java
  app/src/main/java/com/platform/APIClient.java
  app/src/main/java/com/platform/tools/KVStoreManager.java
  install_time_asset_pack/src/main/assets/canary-file.json
Labels: 🦟 critical bug

#260 fix: [#152] make sure using Fragment, FragmentManager and more
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentFingerprint.java
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentPin.java
  app/src/main/java/com/breadwallet/tools/animation/BRAnimator.java
  app/src/main/java/com/breadwallet/tools/security/AuthManager.java
  app/src/main/java/com/breadwallet/tools/security/BRSender.java
Labels: 🐛 bug

#270 fix: [#264] add null checking for BRKeyStore.removeAliasAndFiles
  app/src/main/java/com/breadwallet/tools/security/BRKeyStore.java
Labels: 🐛 bug

#276 revert minSDkVersion to 29
  app/build.gradle
Labels: android, 🦺 tech debt

#277 fix: [#258] avoid OOM with cache the result of opsAll, previously called multiple times at onBindViewHolder
  app/src/main/java/com/breadwallet/tools/adapter/TransactionListAdapter.java
Labels: android, 🐛 bug

#284 🦺 [techdebt] Compiled the env: Normalize for the Android Devs
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: 🦺 tech debt

#256 Techdebt/remove auth prompt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/breadwallet/presenter/activities/LoginActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/intro/WriteDownActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/FingerprintActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/SecurityCenterActivity.java
  app/src/main/java/com/breadwallet/presenter/activities/settings/SettingsActivity.java
  app/src/main/java/com/breadwallet/presenter/fragments/FragmentFingerprint.java
  app/src/main/java/com/breadwallet/tools/manager/PromptManager.java
  app/src/main/java/com/breadwallet/tools/security/AuthManager.java
  app/src/main/java/com/breadwallet/tools/security/BRSender.java
  app/src/main/java/com/breadwallet/tools/threads/PaymentProtocolTask.java
  app/src/main/java/com/breadwallet/tools/util/Utils.java
  app/src/main/res/layout/activity_pin.xml
  app/src/main/res/layout/fingerprint_dialog_container.xml
Labels: 🐛 bug, 🦺 tech debt
